### ISSUE TITLE
Add 'mocks' as an e2e-deploy service set

### ISSUE THREAD

**Issue by bsquizz** [RedHatInsights/mocks#3]
Make `mocks` deployable via e2e-deploy.

1. Create the templates and add a service set
2. Take the logic executed in `deploy/deploy.sh` and add it to a custom `post_deploy` function in that service set.
3. Control whether the mock rbac/entitlements is turned "on" or "off" by wrapping the `Service` in `deploy/deploy.yaml` with an `if` statement -- so that the "real" rbac or entitlements can be deployed in a test environment if desired

**Comment by bsquizz** [comment]
@skarekrow volunteered to pick this up

**Comment by skarekrow** [comment]
PR Here: https://github.com/RedHatInsights/e2e-deploy/pull/2533
